"""Initial migration

Revision ID: b02e7fab7c97
Revises: 
Create Date: 2026-10-07 21:32:39.624406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.generation_job


# revision identifiers, used by Alembic.
revision: str = 'b02e7fab7c97'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generation_jobs',
    sa.Column('id', app.models.generation_job.GUID(), nullable=False),
    sa.Column('event_name', sa.String(), nullable=False),
    sa.Column('completion_date', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('total_count', sa.Integer(), nullable=True),
    sa.Column('success_count', sa.Integer(), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('certificates',
    sa.Column('id', app.models.generation_job.GUID(), nullable=False),
    sa.Column('job_id', app.models.generation_job.GUID(), nullable=False),
    sa.Column('recipient_name', sa.String(), nullable=False),
    sa.Column('recipient_email', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['generation_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('certificates')
    op.drop_table('generation_jobs')
    # ### end Alembic commands ###
